<?php
/**
 * @file
 * Module file for distill.
 */

/**
 * Processor for fields of type 'integer'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_integer(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'float'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_float(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'decimal'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_decimal(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'list_float'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_list_float(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'string'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_string(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'string_long'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_string_long(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'list_string'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_list_string(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'text'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_text(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'text_long'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_text_long(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'text_with_summary'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_text_with_summary(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'boolean'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_boolean(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'file'.
 *
 * @param Drupal\file\Plugin\Field\FieldType\FileFieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_file(Drupal\file\Plugin\Field\FieldType\FileFieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'image'.
 *
 * @param Drupal\image\Plugin\Field\FieldType\ImageItem $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_image(Drupal\image\Plugin\Field\FieldType\ImageItem $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'entity_reference'.
 *
 * @param Drupal\entity_reference\ConfigurableEntityReferenceItem $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_entity_reference(Drupal\entity_reference\ConfigurableEntityReferenceItem $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'link'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_link(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'datetime'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_datetime(Drupal\datetime\Plugin\Field\FieldType\DateTimeFieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'created'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_created(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'changed'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_changed(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'uuid'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_uuid(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'language'.
 *
 * @param Drupal\Core\Field\FieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_language(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'path'.
 *
 * @param Drupal\path\Plugin\Field\FieldType\PathFieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_path(Drupal\path\Plugin\Field\FieldType\PathFieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'comment'.
 *
 * @param Drupal\path\Plugin\Field\FieldType\PathFieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_comment(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}

/**
 * Processor for fields of type 'email'.
 *
 * @param Drupal\path\Plugin\Field\FieldType\PathFieldItemList $field
 *   Object representing a configurable field on an entity.
 * @param int $index
 *   Delta of field being processed.
 * @param array $settings
 *   Processor configuration and context.
 *
 * @return string
 *   Processed value of field.
 */
function distill_distill_process_email(Drupal\Core\Field\FieldItemList $field, $index, array $settings) {
  return $field->getValue();
}
